services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST_DB=db
    depends_on:
      - db
      - redis
    restart: "on-failure"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=reddit_sentiment_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD_DB}  # reference from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
