version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST_DB=db
      - NAME_DB=reddit_sentiment_tracker
      - USER_DB=app_user
      - PASSWORD_DB=app_password
      - PORT_DB=5432
      - JWT_KEY=your_jwt_secret_here
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=reddit_sentiment_tracker
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
